/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Comment } from './models/comment';
export type { CreateCommentRequest } from './models/create-comment-request';
export type { CreateReviewDto } from './models/create-review-dto';
export type { CreateReviewDtoItem } from './models/create-review-dto-item';
export type { GetFileContentRequest } from './models/get-file-content-request';
export type { PullRequest } from './models/pull-request';
export type { PullRequestFile } from './models/pull-request-file';
export type { PullRequestStatus } from './models/pull-request-status';
export type { Recommendation } from './models/recommendation';
export type { RecommendationStatus } from './models/recommendation-status';
export type { RecommendationType } from './models/recommendation-type';
export type { Repository } from './models/repository';
export type { ReviewResult } from './models/review-result';
export type { User } from './models/user';
