/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json } from '../fn/review/api-repositories-repository-id-pull-requests-pull-request-number-review-get-json';
import { ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json$Params } from '../fn/review/api-repositories-repository-id-pull-requests-pull-request-number-review-get-json';
import { apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain } from '../fn/review/api-repositories-repository-id-pull-requests-pull-request-number-review-get-plain';
import { ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain$Params } from '../fn/review/api-repositories-repository-id-pull-requests-pull-request-number-review-get-plain';
import { apiReviewsPatch } from '../fn/review/api-reviews-patch';
import { ApiReviewsPatch$Params } from '../fn/review/api-reviews-patch';
import { apiReviewsPost } from '../fn/review/api-reviews-post';
import { ApiReviewsPost$Params } from '../fn/review/api-reviews-post';
import { ReviewResult } from '../models/review-result';

@Injectable({ providedIn: 'root' })
export class ReviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet()` */
  static readonly ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGetPath = '/api/repositories/{repositoryId}/pull-requests/{pullRequestNumber}/review';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain$Response(params: ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewResult>> {
    return apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain(params: ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain$Params, context?: HttpContext): Observable<ReviewResult> {
    return this.apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReviewResult>): ReviewResult => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json$Response(params: ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewResult>> {
    return apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json(params: ApiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json$Params, context?: HttpContext): Observable<ReviewResult> {
    return this.apiRepositoriesRepositoryIdPullRequestsPullRequestNumberReviewGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReviewResult>): ReviewResult => r.body)
    );
  }

  /** Path part for operation `apiReviewsPost()` */
  static readonly ApiReviewsPostPath = '/api/reviews';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiReviewsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiReviewsPost$Response(params: ApiReviewsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiReviewsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiReviewsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiReviewsPost(params: ApiReviewsPost$Params, context?: HttpContext): Observable<void> {
    return this.apiReviewsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiReviewsPatch()` */
  static readonly ApiReviewsPatchPath = '/api/reviews';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiReviewsPatch()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiReviewsPatch$Response(params: ApiReviewsPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiReviewsPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiReviewsPatch$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiReviewsPatch(params: ApiReviewsPatch$Params, context?: HttpContext): Observable<void> {
    return this.apiReviewsPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
