/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RepositoryHook {
  active?: boolean;
  config?: ({
[key: string]: string;
}) | null;
  createdAt?: string;
  events?: Array<string> | null;
  id?: number;
  name?: string | null;
  pingUrl?: string | null;
  testUrl?: string | null;
  updatedAt?: string;
  url?: string | null;
}
