/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Comment } from './models/comment';
export type { CreateCommentRequest } from './models/create-comment-request';
export type { ReviewResultResponse } from './models/review-result-response';
export type { ReviewResultResponseItem } from './models/review-result-response-item';
