/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReviewDtoItem {
  beginsAtCodeLine?: number;
  description?: string | null;
  endsAtCodeLine?: number;
  file?: string | null;
}
