/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';
import { CreateCommentRequest } from '../../models/create-comment-request';

export interface ApiCommentsPost$Json$Params {

/**
 * GitHub User Access Token
 */
  access_token: string;
      body?: CreateCommentRequest
}

export function apiCommentsPost$Json(http: HttpClient, rootUrl: string, params: ApiCommentsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Comment>> {
  const rb = new RequestBuilder(rootUrl, apiCommentsPost$Json.PATH, 'post');
  if (params) {
    rb.header('access_token', params.access_token, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Comment>;
    })
  );
}

apiCommentsPost$Json.PATH = '/api/comments';
