/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Comment {
  createdAt?: string;
  id?: number;
  isFromUser?: boolean;
  recommendationId?: number;
  text?: string | null;
}
