/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateReviewDtoItem } from '../models/create-review-dto-item';
export interface CreateReviewDto {
  bestPractices?: Array<CreateReviewDtoItem> | null;
  enhancements?: Array<CreateReviewDtoItem> | null;
  issues?: Array<CreateReviewDtoItem> | null;
  optimizations?: Array<CreateReviewDtoItem> | null;
  pullRequestNumber?: number;
  repositoryId?: number;
  vulnerabilities?: Array<CreateReviewDtoItem> | null;
}
