/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCommentRequest {
  isFromUser?: boolean;
  recommendationId?: number;
  text?: string | null;
}
