/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetFileContentRequest {
  filePath?: string | null;
  headRef?: string | null;
  repositoryName?: string | null;
}
