/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PullRequestFile {
  additions?: number;
  blobUrl?: string | null;
  changes?: number;
  contentsUrl?: string | null;
  deletions?: number;
  fileName?: string | null;
  patch?: string | null;
  previousFileName?: string | null;
  rawUrl?: string | null;
  sha?: string | null;
  status?: string | null;
}
