/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecommendationStatus } from '../models/recommendation-status';
import { RecommendationType } from '../models/recommendation-type';
export interface Recommendation {
  codeLines?: Array<number> | null;
  content?: string | null;
  createdAt?: string;
  fileName?: string | null;
  id?: number;
  pullRequestNumber?: number;
  repositoryId?: number;
  status?: RecommendationStatus;
  type?: RecommendationType;
}
