/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Repository {
  id?: number;
  name?: string | null;
  owner?: User;
  url?: string | null;
}
