/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  avatarUrl?: string | null;
  id?: number;
  url?: string | null;
  username?: string | null;
}
